/**
 * Ivy in-app chat — the text channel that complements the voice ritual.
 *
 * Same Ivy as the calls: replies are generated by Claude using the SAME persona /
 * memory / standing-rules composer that drives Retell prompts (prompt.service
 * buildSystemPrompt with the 'CHAT' flow), so text-Ivy knows the user, their
 * stake, and their history. Messages persist on the existing Message model
 * (channel IN_APP, direction INBOUND=user / OUTBOUND=Ivy) so chat lives in one
 * log alongside SMS/Telegram.
 *
 * Reuses: callService.getUserContext (context), promptService.buildSystemPrompt
 * (system prompt), the established Anthropic pattern from brief/insight services,
 * push.service for background notifications.
 */

import Anthropic from '@anthropic-ai/sdk'
import prisma from '../utils/prisma'
import logger from '../utils/logger'
import callService from './call.service'
import { promptService } from './prompt.service'
import * as pushService from './push.service'
import { logUsage } from './usage.service';

const MODEL = 'claude-haiku-4-5'
const HISTORY_LIMIT = 20 // recent turns sent to the model
const MAX_TOKENS = 300 // texts are short

type IvyAction = 'call_now' | 'schedule' | 'just_text'

class ChatService {
  private client: Anthropic | null = null

  constructor() {
    if (process.env.ANTHROPIC_API_KEY) {
      this.client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
    }
  }

  /** Full IN_APP thread for a user, oldest → newest (UI renders bottom-anchored). */
  async getThread(userId: string, limit = 100) {
    const rows = await prisma.message.findMany({
      where: { userId, channel: 'IN_APP' },
      orderBy: { createdAt: 'desc' },
      take: limit,
    })
    return rows.reverse()
  }

  /** Count of unread Ivy (OUTBOUND) messages — drives the nav badge. */
  async getUnreadCount(userId: string): Promise<number> {
    return prisma.message.count({
      where: { userId, channel: 'IN_APP', direction: 'OUTBOUND', status: { not: 'READ' } },
    })
  }

  /** Mark all Ivy messages read (called when the user opens the thread). */
  async markRead(userId: string): Promise<void> {
    await prisma.message.updateMany({
      where: { userId, channel: 'IN_APP', direction: 'OUTBOUND', status: { not: 'READ' } },
      data: { status: 'READ' },
    })
  }

  /**
   * Post a proactive Ivy message (onboarding handoff, evening check-in). No model
   * call — the content is supplied. Used by Day-Zero + the evening scheduler.
   */
  async postIvyMessage(
    userId: string,
    content: string,
    opts: { messageType?: string; metadata?: any; notify?: boolean } = {},
  ) {
    const msg = await prisma.message.create({
      data: {
        userId,
        channel: 'IN_APP',
        direction: 'OUTBOUND',
        content,
        status: 'SENT',
        messageType: opts.messageType ?? 'chat',
        metadata: opts.metadata ?? undefined,
      },
    })
    if (opts.notify !== false) await this.notify(userId, content)
    return msg
  }

  /**
   * User sends a message → persist it, generate Ivy's reply with full context,
   * persist + return the reply. Falls back to a graceful canned line if the LLM
   * is unavailable (no key / error) so the thread never dead-ends.
   */
  async sendUserMessage(userId: string, content: string) {
    const text = content.trim()
    if (!text) throw new Error('Empty message')

    await prisma.message.create({
      data: { userId, channel: 'IN_APP', direction: 'INBOUND', content: text, status: 'READ', messageType: 'chat' },
    })

    // Coaches can state programme changes in chat ("move Tom to 3x a week") —
    // extract + apply BEFORE generating the reply, so Ivy confirms what
    // actually happened instead of promising vaguely. Only worth a model call
    // when the message plausibly names a client.
    let appliedNote: string | undefined
    const user = await prisma.user.findUnique({ where: { id: userId }, select: { subscriptionTier: true } })
    if (user?.subscriptionTier === 'COACH') {
      appliedNote = await this.applyCoachProgrammeChanges(userId, text)
    }

    const reply = await this.generateReply(userId, appliedNote)

    const ivyMsg = await prisma.message.create({
      data: { userId, channel: 'IN_APP', direction: 'OUTBOUND', content: reply, status: 'SENT', messageType: 'chat' },
    })

    return ivyMsg
  }

  /**
   * Run programme-update extraction on a coach's chat message when it mentions
   * one of their clients by first name. Returns a note describing what was
   * applied (for the reply prompt), or undefined when nothing ran/matched.
   */
  private async applyCoachProgrammeChanges(coachId: string, text: string): Promise<string | undefined> {
    try {
      const clients = await prisma.user.findMany({
        where: { coachId },
        select: { firstName: true },
      })
      const lower = text.toLowerCase()
      const mentionsClient = clients.some(
        (c) => c.firstName && c.firstName.length > 2 && lower.includes(c.firstName.toLowerCase()),
      )
      if (!mentionsClient) return undefined

      const coachService = (await import('./coach.service')).default
      const applied = await coachService.extractAndApplyProgrammeUpdates(coachId, text, 'chat')
      if (applied.length === 0) return undefined
      return applied
        .map((u) => `${u.clientName} — ${u.area}: ${u.instruction === 'REMOVE' ? 'removed' : u.instruction}`)
        .join('\n')
    } catch (err) {
      logger.warn(`Coach chat programme extraction failed for ${coachId}:`, err)
      return undefined
    }
  }

  /** Action-button taps on an Ivy card (onboarding handoff). */
  async handleAction(userId: string, action: IvyAction, payload?: { at?: string }) {
    switch (action) {
      case 'call_now': {
        // Soonest practical slot — a couple of minutes out so the scheduler picks it up.
        const at = new Date(Date.now() + 2 * 60 * 1000)
        await callService.scheduleCall(userId, 'ONBOARDING', at, await callService.getUserContext(userId, 'ONBOARDING'))
        return this.postIvyMessage(userId, `Calling you in a minute or two. Pick up — it's quick.`, { notify: false })
      }
      case 'schedule': {
        const at = payload?.at ? new Date(payload.at) : null
        if (!at || isNaN(at.getTime())) throw new Error('A valid time is required to schedule')
        await callService.scheduleCall(userId, 'ONBOARDING', at, await callService.getUserContext(userId, 'ONBOARDING'))
        return this.postIvyMessage(userId, `Locked in. I'll call you then.`, { notify: false })
      }
      case 'just_text': {
        await prisma.user.update({ where: { id: userId }, data: { commStyle: 'TEXTS' } })
        return this.postIvyMessage(
          userId,
          `Text it is. I'll check in with you right here each day instead of calling. So — what are you taking on?`,
          { notify: false },
        )
      }
      default:
        throw new Error(`Unknown action: ${action}`)
    }
  }

  // ── internals ────────────────────────────────────────────────────────────────

  private async generateReply(userId: string, appliedNote?: string): Promise<string> {
    const FALLBACK = `I'm here — say a bit more and I'll help you sort it.`
    if (!this.client) return FALLBACK

    try {
      const [ctx, user, history] = await Promise.all([
        callService.getUserContext(userId, 'CHAT'),
        prisma.user.findUnique({ where: { id: userId }, select: { subscriptionTier: true, commStyle: true, firstName: true } }),
        this.getThread(userId, HISTORY_LIMIT),
      ])

      const isB2B = user?.subscriptionTier === 'B2B'
      ctx.comm_preference = user?.commStyle ?? ctx.comm_preference
      const system = user?.subscriptionTier === 'COACH'
        ? await this.buildCoachChatSystem(userId, user.firstName ?? 'Coach', appliedNote)
        : promptService.buildSystemPrompt('CHAT', ctx, isB2B)

      const messages = history.map((m) => ({
        role: (m.direction === 'INBOUND' ? 'user' : 'assistant') as 'user' | 'assistant',
        content: m.content,
      }))
      // Anthropic requires the turn list to start with a user message.
      while (messages.length && messages[0].role !== 'user') messages.shift()
      if (!messages.length) return FALLBACK

      const res = await this.client.messages.create({
        model: MODEL,
        max_tokens: MAX_TOKENS,
        system: [{ type: 'text', text: system, cache_control: { type: 'ephemeral' } }] as any,
        messages,
      })

      const reply = res.content[0]?.type === 'text' ? res.content[0].text.trim() : ''
      logUsage('anthropic', 'haiku_tokens', (res.usage?.input_tokens ?? 0) + (res.usage?.output_tokens ?? 0), userId, { op: 'chat_reply' }).catch(() => {})
      return reply || FALLBACK
    } catch (err) {
      logger.error(`Ivy chat reply failed for ${userId}:`, err)
      return FALLBACK
    }
  }

  /**
   * System prompt for COACH chat — the same colleague who runs the ponder
   * calls, in text form. Grounded in the live roster brief so she can answer
   * "how's Sarah doing" with real data, and told exactly what programme
   * changes were just applied so confirmations are precise, never vague.
   */
  private async buildCoachChatSystem(coachId: string, coachName: string, appliedNote?: string): Promise<string> {
    let rosterBrief = ''
    try {
      const coachService = (await import('./coach.service')).default
      rosterBrief = await coachService.generatePonderBrief(coachId)
    } catch { /* roster unavailable — Ivy still replies, just without data */ }

    return [
      `You are Ivy, texting with ${coachName} — a professional coach you work WITH. You run the daily accountability for their clients (morning voice notes, evening settles, the money on the line) and report back what you see. This chat is the text side of your working relationship; the biweekly ponder call is the voice side.`,
      '',
      `TEXTING STYLE: short. One to three sentences unless they ask for a rundown. A colleague on WhatsApp, not a report. React to what they said first. Never bullet-point lists unless they ask for a summary.`,
      '',
      rosterBrief,
      '',
      appliedNote
        ? `JUST APPLIED (from their last message — already saved to the programme, the client will be notified): \n${appliedNote}\nConfirm this naturally and precisely — repeat back what changed in your own words. Do not claim anything beyond these exact changes.`
        : `PROGRAMME CHANGES: when they state a change for a named client ("move Tom to 3x a week"), it is extracted and applied automatically. If you see no JUST APPLIED block for a change they clearly requested, it did NOT apply — tell them to phrase it with the client's name and the specific change, don't pretend it worked.`,
      '',
      `Never invent client data — if it's not in your notes above, say you'll check. Slip alerts and ponder summaries also arrive in this thread, so they may reference those.`,
      '',
      `NEVER: open with "Great!"/"Absolutely!" or filler; talk to a coach about THEIR streaks/stakes (they have none — they're a partner, not a member); oversell — you're a colleague reporting from the field, and understatement lands better with professionals.`,
    ].filter(Boolean).join('\n')
  }

  private async notify(userId: string, content: string): Promise<void> {
    try {
      await pushService.sendPushToUser(userId, {
        title: 'Ivy',
        body: content.length > 120 ? `${content.slice(0, 117)}…` : content,
        tag: 'ivy-chat',
        url: '/ivy',
      })
    } catch (err) {
      logger.warn(`Chat push notify failed for ${userId}:`, err)
    }
  }
}

export default new ChatService()
